version: '3.9'

services:
  # service that simulates ethereum mainnet
  eth-ganache:
    container_name: eth-ganache
    image: audius/eth-ganache:latest
    ports:
      - "8546:8545"
  
  # service that simulates solana mainnet
  sol-validator:
    container_name: solana-test-validator
    image: audius/solana-programs:latest
    ports:
      - "8899:8899"

  # service that simulates acdc network
  acdc-ganache:
    container_name: acdc-ganache
    image: audius/acdc-ganache:latest
    ports:
      - "8545:8545"

  ingress:
    container_name: ingress
    image: openresty/openresty:1.21.4.1-alpine-fat
    volumes:
      - ./nginx_ingress.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
