# creator-node
creatorNodeEndpoint=https://localhost
delegateOwnerWallet=
delegatePrivateKey=
spOwnerWallet=

# discovery-provider
audius_discprov_url=https://localhost
audius_delegate_owner_wallet=
audius_delegate_private_key=
