#!/bin/sh
ARCH=$(uname -m)
if [ "$ARCH" = "arm64" ]; then
    BINARY_NAME="audius-ctl-arm"
    make bin/audius-ctl-arm
else
    BINARY_NAME="audius-ctl-x86"
    make bin/audius-ctl-x86
fi

./bin/$BINARY_NAME "$@"
