version: 2.1

orbs:
  gh: circleci/github-cli@2.2.0

jobs:
  standup-dot-slash:
    machine:
      image: ubuntu-2204:current
    resource_class: large
    steps:
      - checkout:
          path: ~/dot-slash-audius
      - run:
          name: make
          command: cd ~/dot-slash-audius && make
      # - run:
      #     name: build push audius-docker-compose
      #     command: cd ~/dot-slash-audius && make build-push
      - run:
          name: populate config
          command: |
            mkdir ~/.audius
            echo "creatorNodeEndpoint=https://localhost" >> ~/.audius/creator.conf
            echo "delegateOwnerWallet=$delegateOwnerWallet" >> ~/.audius/creator.conf
            echo "delegatePrivateKey=$delegatePrivateKey" >> ~/.audius/creator.conf
            echo "spOwnerWallet=$spOwnerWallet" >> ~/.audius/creator.conf
            echo "audius_discprov_url=https://localhost" >> ~/.audius/discovery.conf
            echo "audius_delegate_owner_wallet=$audius_delegate_owner_wallet" >> ~/.audius/discovery.conf
            echo "audius_delegate_private_key=$audius_delegate_private_key" >> ~/.audius/discovery.conf
      - run:
          name: start audius nodes
          command: |
            cd ~/dot-slash-audius
            ./bin/audius-x86 -c ~/.audius/creator.conf --local
            # Disabled temporarily
            # ./bin/audius-x86 -c ~/.audius/discovery.conf --local --port 8080 --tls 8081
      - run:
          name: check audius node health
          command: |
            timeout=0
            while [ "$(curl -sko /dev/null -w "%{http_code}" https://localhost/health_check)" = 502 ] && [ "$timeout" -lt 60 ]; do
              sleep 3
              ((timeout=timeout+3))
              echo "Waiting for server to start... $timeout"
            done

            cresult="$(curl -Lkv https://localhost/health_check | jq '.data.healthy')"
            # dresult="$(curl -Lkv https://localhost:8081/health_check | jq '.data.healthy')"
            [ "$cresult" = true ] || [ "$cresult" = false ]
            # [ "$dresult" = true ] || [ "$dresult" = false ]

  build-pub-go:
    docker:
      # - image: cimg/base:2023.01
      - image: golang:latest
    steps:
      - checkout:
          path: ~/dot-slash-audius
      - gh/setup:
          version: 2.23.0
      - add_ssh_keys:
            fingerprints:
              - "7a:85:bb:bf:30:0e:99:c9:d5:ba:9e:a5:05:c8:cf:12"
      - run:
          name: Set git config
          command: |
            git config --global user.email "audius-infra@audius.co"
            git config --global user.name "audius-infra"
      - run:
          command: |
            cd ~/dot-slash-audius
            git checkout -b foo
            make
            git add bin/*
            git commit -m "Update golang bin $CIRCLE_SHA1"
            git push -f -u origin foo

workflows:
  dot-slash:
    jobs:
      - build-pub-go:
          context: github
          filters:
            branches:
              only:
                - build
      - standup-dot-slash:
          context: dot-slash-audius
          filters:
            branches:
              ignore:
                - main
