# Root CircleCI configuration
# Configuration for individual packages lives in .circleci/src/{commands,jobs,workflows}

version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1

parameters:
  workflow:
    type: string
    default: 'main'

jobs:
  # Generate the CircleCI continue_config.yml from .circleci/src
  generate-config:
    executor: continuation/default
    steps:
      # The circleci cli exposed in the image doesn't support config packing
      # so we install a version that does
      - run:
          name: Install cli
          command: curl -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh | DESTDIR=~/cli bash
      - checkout
      - run:
          name: Generate config
          command: ~/cli config pack .circleci/src > .circleci/continue_config.yml
      - continuation/continue:
          configuration_path: .circleci/continue_config.yml

workflows:
  setup:
    jobs:
      - generate-config
