build:
  machine:
    image: ubuntu-2204:current
  resource_class: large
  steps:
    - attach_workspace:
        at: ~/workspace
    - checkout:
        path: ~/audius-d
    - gh/setup
    - run:
        name: install go
        command: |
          sudo apt-get update
          sudo apt-get install -y golang
    - run:
        name: Build audius-docker-compose docker image
        command: |
          cd ~/audius-d

          REPO_OWNER="AudiusProject"
          REPO_NAME="audius-docker-compose"
          BRANCH_NAME="stage"
          COMPOSE_COMMIT_SHA=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/branches/$BRANCH_NAME" | \
            jq -r '.commit.sha')
          DOCKER_IMAGE="audius/audius-docker-compose:$COMPOSE_COMMIT_SHA"

          echo "export COMPOSE_COMMIT_SHA=$COMPOSE_COMMIT_SHA" >> $BASH_ENV

          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          
          if docker buildx imagetools inspect $DOCKER_IMAGE >/dev/null 2>&1; then
            echo "Docker image $DOCKER_IMAGE already exists. Skipping build."
          else
            echo "Docker image $DOCKER_IMAGE not found. Building and pushing..."
            docker buildx create --use
            make build-push-docker ADC_TAG=$COMPOSE_COMMIT_SHA
            make build-push-docker ADC_TAG=latest
          fi
    - restore_cache:
        keys:
          - node-modules-{{ checksum "~/audius-d/web/ui/package-lock.json" }}
          - node-modules-
    - run:
        name: Build audius-ctl for production
        command: |
          cd ~/audius-d
          make audius-ctl-production-build
    - save_cache:
        key: node-modules-{{ checksum "~/audius-d/web/ui/package-lock.json" }}
        paths:
          - ~/audius-d/web/ui/node_modules
    - persist_to_workspace:
        root: ~/audius-d
        paths:
          - bin/audius-ctl-arm
          - bin/audius-ctl-x86
