publish-audius-ctl:
  docker:
    - image: cimg/base:2023.01
  resource_class: small
  steps:
    - checkout:
        path: ~/audius-d
    - attach_workspace:
        at: ~/audius-d
    - gh/setup
    - run:
        name: Release 
        command: |
          cd ~/audius-d
          make release-audius-ctl
