test-config-subcommands:
  machine:
    image: ubuntu-2204:current
  resource_class: medium
  steps:
    - setup-audius-ctl
    - run:
        name: test default context is created
        command: |
          audius-ctl config
    - run:
        name: test create context
        command: |
          audius-ctl config create-context test -f ~/audius-d/configs/templates/ci.toml 
    - run:
        name: test modify context
        command: |
          audius-ctl config set Network.EthMainnetRpc test-str
          audius-ctl config | grep 'EthMainnetRpc = "test-str"'
    - run:
        name: test invalid modify context
        command: |
          if audius-ctl config set Network.Devnet 420; then
            echo Should not have succeeded due to type error
            false
          fi
          audius-ctl config | grep 'EthMainnetRpc = "test-str"'
    - run:
        name: test delete context
        command: |
          audius-ctl config delete-context test
          audius-ctl config  # should resort to default
          audius-ctl config current-context | grep 'default'
