test-devnet-deps:
  machine:
    image: ubuntu-2204:current
  resource_class: large
  steps:
    - setup-audius-ctl
    - run: audius-ctl devnet
    - run: docker ps
    - run:
        name: Wait for acdc-ganache to start
        command: |
          timeout=0
          while [[ "$(curl -sf -w "%{http_code}" -o /dev/null -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' http://localhost:8545)" =~ 502|000 ]] && [ "$timeout" -lt 60 ]; do
            sleep 3
            ((timeout=timeout+3))
            echo "Waiting for server to start... $timeout"
          done
          if [ "$timeout" -ge 60 ]; then
            echo "Server didn't respond within 60 seconds. Exiting due to timeout."
            exit 1
          fi
    - run:
        name: Wait for mainnet-ganache to start
        command: |
          timeout=0
          while [[ "$(curl -sf -w "%{http_code}" -o /dev/null -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' http://localhost:8546)" =~ 502|000 ]] && [ "$timeout" -lt 60 ]; do
            sleep 3
            ((timeout=timeout+3))
            echo "Waiting for server to start... $timeout"
          done
          if [ "$timeout" -ge 60 ]; then
            echo "Server didn't respond within 60 seconds. Exiting due to timeout."
            exit 1
          fi
    - run:
        name: Wait for mainnet-solana to start
        command: |
          timeout=0
          while [[ "$(curl http://localhost:8899 -o /dev/null -X POST -H "Content-Type: application/json" -w "%{http_code}" -d '{"jsonrpc":"2.0","id":1,"method":"getFirstAvailableBlock"}')" =~ 502|000 ]] && [ "$timeout" -lt 60 ]; do
            sleep 3
            ((timeout=timeout+3))
            echo "Waiting for server to start... $timeout"
          done
          if [ "$timeout" -ge 60 ]; then
            echo "Server didn't respond within 60 seconds. Exiting due to timeout."
            exit 1
          fi
    - run: audius-ctl devnet down
