test-audius-d-devnet:
  machine:
    image: ubuntu-2204:current
  resource_class: large
  steps:
    - setup-audius-ctl
    - run:
        name: standup isolated ci env
        command: |
          cd ~/audius-d
          audius-ctl config create-context ci -f configs/templates/devnet.toml 
          audius-ctl up
    - basic-health-check # creator node default
    - basic-health-check:
        port: 5000
        jqkey: '.data.discovery_provider_healthy'
    - basic-health-check:
        port: 7000
        jqkey: '.healthy'
    - run: audius-ctl down
