title = "Default Devnet Configuration"
description = """
defaults for an isolated devnet configuration of audius protocol with audius-d
values taken straight from audius-docker-compose
"""

[Network]
Name = "devnet"

AcdcRpc = "http://host.docker.internal"
AcdcPort = 8545

EthMainnetRpc = "http://eth-ganache"
EthMainnetPort = 8546

SolanaMainnetRpc = "http://host.docker.internal"
SolanaMainnetPort = 8899

Tag = "latest"

[CreatorNodes]

[CreatorNodes.creator-1]
Host = "http://localhost"
ExternalHttpPort = 80
InternalHttpPort = 80
ExternalHttpsPort = 443
InternalHttpsPort = 443
OperatorPrivateKey = "62ca4962f99a39b4a2c60a8402f60baea5437c275146abd90e0bfdcf0415184d"

# creator specific config
HostNameTemplate = "http://audius-protocol-creator-node-%d"
IdentityService = "http://host.docker.internal:7000"
Web3EthProviderUrl = "http://host.docker.internal:8546"           # Used only in register script
EthProviderUrl = "http://host.docker.internal:8546"
EthRegistryAddress = '0xABbfF712977dB51f9f212B85e8A4904c818C2b63'


[DiscoveryNodes]

[DiscoveryNodes.discovery-1]
Host = "http://localhost"
ExternalHttpPort = 5000
InternalHttpPort = 5000
ExternalHttpsPort = 5001
InternalHttpsPort = 5001
OperatorPrivateKey = ""

# discovery specific config
AudiusWeb3Host = 'http://host.docker.internal:8545'
AudiusWeb3EthProviderUrl = 'http://host.docker.internal:8546'
AudiusContractsRegistry = '0xCfEB869F69431e42cdB54A4F4f105C19C080A601'
AudiusContractsEntityManagerAddress = '0x254dffcd3277C0b1660F6d42EFbB754edaBAbC2B'
AudiusEthContractsRegistry = '0xABbfF712977dB51f9f212B85e8A4904c818C2b63'
AudiusEthContractsToken = '0xdcB2fC9469808630DD0744b0adf97C0003fC29B2'

AudiusSolanaEndpoint = 'http://host.docker.internal:8899'
AudiusSolanaTrackListenCountAddress = 'testEjzEibm3nq77VQcqCCmSMx6m3KdJHuepBH1rnue'
AudiusSolanaSignerGroupAddress = 'HwecRT7whduwiLhJXiWmvrhcCh8zJhwJ4B9fXniPUDyz'
AudiusSolanaUserBankProgramAddress = 'testHKV1B56fbvop4w6f2cTGEub9dRQ2Euta5VmqdX9'
AudiusSolanaWaudioMint = '37RCjhgV1qGV2Q54EHFScdxZ22ydRMdKMtVgod47fDP3'
AudiusSolanaUsdcMint = '26Q7gP8UfkDzi7GMFEQxTJaNJ8D2ybCUjex58M5MLu8y'
AudiusSolanaRewardsManagerProgramAddress = 'testLsJKtyABc9UXJF8JWFKf1YH4LmqCWBC42c6akPb'
AudiusSolanaRewardsManagerAccount = 'DJPzVothq58SmkpRb1ATn5ddN2Rpv1j2TcGvM3XsHf1c'
AudiusSolanaAnchorDataProgramId = 'testRaQeeuPVd4RK4ae1sHE3xcAQyFuPHBFoVwXWc4k'
AudiusSolanaAnchorAdminStoragePublicKey = '2Vb2BiY8d3qYkHhnMdmJQqBXv6NUtSik1Bw2nRYeP46w'

AudiusDiscprovDevMode = 'true'
AudiusDiscprovLoglevel = 'debug'


[IdentityService]

[IdentityService.identity-1]
Host = "http://localhost"
ExternalHttpPort = 7000
InternalHttpPort = 7000
ExternalHttpsPort = 7001
InternalHttpsPort = 7001

# identity specific config
LogLevel = "debug"
MinimumBalance = 1
MinimumRelayerBalance = 1
MinimumFunderBalance = 1

RelayerPrivateKey = '34efbbc0431c7f481cdba15d65bbc9ef47196b9cf38d5c4b30afa2bcf86fafba'
RelayerPublicKey = '0xaaaa90Fc2bfa70028D6b444BB9754066d9E2703b'
RelayerWallets = '[{"publicKey": "0xaaaa90Fc2bfa70028D6b444BB9754066d9E2703b", "privateKey": "34efbbc0431c7f481cdba15d65bbc9ef47196b9cf38d5c4b30afa2bcf86fafba"}, {"publicKey": "0xBE718F98a5B5a473186eB6E30888F26E72be0b66", "privateKey": "d3426cd10c4e75207bdc4802c551d21faa89a287546c2c6b3d9a0476f34934d2"}]'

EthFunderAddress = "0xaaaa90Fc2bfa70028D6b444BB9754066d9E2703b"
EthRelayerWallets = '[{"publicKey": "0xE75dEe171b6472cE30358ede946CcDFfCA70b562", "privateKey": "8a7c63d4aea87647f480e4771ea279f90f8e912fcfe907525bc931f531e564ce"}, {"publicKey": "0xBE718F98a5B5a473186eB6E30888F26E72be0b66", "privateKey": "d3426cd10c4e75207bdc4802c551d21faa89a287546c2c6b3d9a0476f34934d2"}, {"publicKey": "0xaaaa90Fc2bfa70028D6b444BB9754066d9E2703b", "privateKey": "34efbbc0431c7f481cdba15d65bbc9ef47196b9cf38d5c4b30afa2bcf86fafba"}]'

UserVerifierPrivateKey = "ebba299e6163ff3208de4e82ce7db09cf7e434847b5bdab723af96ae7c763a0e"
UserVerifierPublicKey = "0xbbbb93A6B3A1D6fDd27909729b95CCB0cc9002C0"

DbUrl = "postgres://postgres:postgres@db:5432/identity_service"

RedisHost = "redis"
RedisPort = 6379

AaoEndpoint = "http://anti-abuse-oracle:8000"
AaoAddress = '0xF0D5BC18421fa04D0a2A2ef540ba5A9f04014BE3'

Web3Provider = "http://host.docker.internal:8545"
SecondaryWeb3Provider = "http://host.docker.internal:8545"
RegistryAddress = '0xCfEB869F69431e42cdB54A4F4f105C19C080A601'
EntityManagerAddress = '0x254dffcd3277C0b1660F6d42EFbB754edaBAbC2B'
OwnerWallet = '0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1'

EthProviderUrl = "http://host.docker.internal:8546"
EthTokenAddress = '0xdcB2fC9469808630DD0744b0adf97C0003fC29B2'
EthRegistryAddress = '0xABbfF712977dB51f9f212B85e8A4904c818C2b63'
EthOwnerWallet = '0x855FA758c77D68a04990E992aA4dcdeF899F654A'

SolanaEndpoint = "http://host.docker.internal:8899"
SolanaTrackListenCountAddress = 'testEjzEibm3nq77VQcqCCmSMx6m3KdJHuepBH1rnue'
SolanaAudiusEthRegistryAddress = 'testBgRfFcage1hN7zmTsktdQCJZkHEhM1eguYPaeKg'
SolanaValidSigner = 'yM9adjwKaRbYxQzLPF6zvZMSAfKUNte5xvK4B3iGbkL'
SolanaFeePayerWallets = '[{"privateKey":"[170, 161, 84, 122, 118, 210, 128, 213, 96, 185, 143, 218, 54, 254, 217, 204, 157, 175, 137, 71, 202, 108, 51, 242, 21, 50, 56, 77, 54, 116, 103, 56, 251, 64, 77, 100, 199, 88, 103, 189, 42, 163, 67, 251, 101, 204, 7, 59, 70, 109, 113, 50, 209, 154, 55, 164, 227, 108, 203, 146, 121, 148, 85, 119]"}]'
SolanaSignerPrivateKey = 'd242765e718801781440d77572b9dafcdc9baadf0269eff24cf61510ddbf1003'
SolanaMintAddress = '37RCjhgV1qGV2Q54EHFScdxZ22ydRMdKMtVgod47fDP3'
SolanaUSDCMintAddress = '26Q7gP8UfkDzi7GMFEQxTJaNJ8D2ybCUjex58M5MLu8y'
SolanaClaimableTokenProgramAddress = 'testHKV1B56fbvop4w6f2cTGEub9dRQ2Euta5VmqdX9'
SolanaRewardsManagerProgramId = 'testLsJKtyABc9UXJF8JWFKf1YH4LmqCWBC42c6akPb'
SolanaRewardsManagerProgramPDA = 'DJPzVothq58SmkpRb1ATn5ddN2Rpv1j2TcGvM3XsHf1c'
SolanaRewardsManagerTokenPDA = 'FRk4j95RG2kSk3BHXBPVgKszFc2rLQ8K6RS83k3dmzvQ'
SolanaAudiusAnchorDataProgramId = 'testRaQeeuPVd4RK4ae1sHE3xcAQyFuPHBFoVwXWc4k'
