title = "Default Devnet Configuration"
description = """
defaults for an isolated devnet configuration of audius protocol with audius-d
"""

[Network]
Name = "devnet"

AcdcRpc = "http://acdc-ganache"
AcdcPort = 8545

EthMainnetRpc = "http://eth-ganache"
EthMainnetPort = 8546

SolanaMainnetRpc = "http://solana-test-validator"
SolanaMainnetPort = 8899

Tag = "latest"

[CreatorNodes]

[CreatorNodes.creator-1]
Host = "http://localhost"
ExternalHttpPort = 80
InternalHttpPort = 80
ExternalHttpsPort = 443
InternalHttpsPort = 443
OperatorPrivateKey = "62ca4962f99a39b4a2c60a8402f60baea5437c275146abd90e0bfdcf0415184d"

[DiscoveryNodes]

[DiscoveryNodes.discovery-1]
Host = "http://localhost"
ExternalHttpPort = 5000
InternalHttpPort = 5000
ExternalHttpsPort = 5001
InternalHttpsPort = 5001
OperatorPrivateKey = ""

[IdentityService]

[IdentityService.identity-1]
Host = "http://localhost"
ExternalHttpPort = 7000
InternalHttpPort = 7000
ExternalHttpsPort = 7001
InternalHttpsPort = 7001
