title = "Example Devnet Configuration"
description = """
example and runnable file for running a devnet configuration of audius protocol with audius-d
"""

[Network]
Name = "devnet"
Tag = "latest"
AcdcRpc = "http://localhost:8545"
EthMainnetRpc = "http://localhost:8546"
SolanaMainnetRpc = "http://localhost:8899"

EthMainnetNetworkId = "1337"
Devnet = true

[CreatorNodes.creator-1]
InternalHttpPort = 80
ExternalHttpPort = 80
InternalHttpsPort = 443
ExternalHttpsPort = 443
Host = "http://localhost"
Tag = "latest"
OperatorPrivateKey = "21118f9a6de181061a2abd549511105adb4877cf9026f271092e6813b7cf58ab"
OperatorWallet = "0x0D38e653eC28bdea5A2296fD5940aaB2D0B8875c"
OperatorRewardsWallet = "0xb3c66e682Bf9a85F6800c769AC5A05c18C3F331d"

MediorumEnv = "sandbox"

[DiscoveryNodes.discovery-1]
InternalHttpPort = 5000
ExternalHttpPort = 5000
InternalHttpsPort = 5001
ExternalHttpsPort = 5001
Host = "http://localhost"
OperatorPrivateKey = "c1c36935d3809daacf3aa63243feef5e7a97ba11dc56fe3a923758937362ed6e"
OperatorWallet = "0xfF4329197C7bD52480567CE6c19331BD37555B3c"
OperatorRewardsWallet = "0xfF4329197C7bD52480567CE6c19331BD37555B3c"

[IdentityService.identity-1]
SolanaClaimableTokenProgramAddress = "testHKV1B56fbvop4w6f2cTGEub9dRQ2Euta5VmqdX9"
InternalHttpPort = 7000
ExternalHttpPort = 7000
InternalHttpsPort = 7001
ExternalHttpsPort = 7001
Host = "http://localhost"
