title = "Example Devnet Configuration"
description = """
example and runnable file for running a devnet configuration of audius protocol with audius-d
"""

[Network]
Name = "devnet"
AudiusComposeNetwork = "dev"
Tag = "alec-test"
Devnet = true

[CreatorNodes.creator-1]
InternalHttpPort = 80
ExternalHttpPort = 80
InternalHttpsPort = 443
ExternalHttpsPort = 443
Host = "http://localhost"
OperatorPrivateKey = "21118f9a6de181061a2abd549511105adb4877cf9026f271092e6813b7cf58ab"
OperatorWallet = "0x0D38e653eC28bdea5A2296fD5940aaB2D0B8875c"
OperatorRewardsWallet = "0xb3c66e682Bf9a85F6800c769AC5A05c18C3F331d"
AwaitHealthy = true
Register = false

[DiscoveryNodes.discovery-1]
InternalHttpPort = 5000
ExternalHttpPort = 5000
InternalHttpsPort = 5001
ExternalHttpsPort = 5001
Host = "http://localhost"
OperatorPrivateKey = "d09ba371c359f10f22ccda12fd26c598c7921bda3220c9942174562bc6a36fe8"
OperatorWallet = "0x73EB6d82CFB20bA669e9c178b718d770C49BB52f"
OperatorRewardsWallet = "0x73EB6d82CFB20bA669e9c178b718d770C49BB52f"
AwaitHealthy = true
Register = false


[IdentityService.identity-1]
InternalHttpPort = 7000
ExternalHttpPort = 7000
InternalHttpsPort = 7001
ExternalHttpsPort = 7001
Host = "http://localhost"
AwaitHealthy = true
