title = "Example Devnet Configuration"
description = """
example and runnable file for running a devnet configuration of audius protocol with audius-d
"""

[Network]
Name = "devnet"

AcdcRpc = "http://acdc-ganache"
AcdcPort = 8545

EthMainnetRpc = "http://eth-ganache"
EthMainnetPort = 8546

SolanaMainnetRpc = "http://solana-test-validator"
SolanaMainnetPort = 8899

Tag = "stage"
Devnet = true

[CreatorNodes]

[CreatorNodes.creator-1]
Host = "http://localhost"
Port = 6000
Tag = "latest"
OperatorPrivateKey = ""
