title = "Example Operator Configuration"
description = """
example of how to run a creator node as an operator with audius-d
"""

[Network]
DeployOn = "mainnet"

[DiscoveryNodes.discovery-node]
HttpPort = 5000
HttpsPort = 5001
Host = "http://localhost"
OperatorPrivateKey = ""
OperatorWallet = ""
OperatorRewardsWallet = ""
