title = "Example Operator Configuration"
description = """
example of how to run a creator node as an operator with audius-d
"""

Network = "mainnet"
# implies auto-upgrade on latest stable (audius-docker-compose/main branch) release
Version = "stable"

[CreatorNodes.creator-node]
InternalHttpPort = 80
ExternalHttpPort = 80
Host = "http://localhost"
OperatorPrivateKey = ""
OperatorWallet = ""
OperatorRewardsWallet = ""
