title = "Example Operator Configuration"
description = """
example of how to run a creator node as an operator with audius-d
"""

[Network]
DeployOn = "mainnet"

[CreatorNodes.creator-node]
HttpPort = 80
HttpsPort = 443
Host = "http://localhost"
Version = "current"
OperatorPrivateKey = ""
OperatorWallet = ""
OperatorRewardsWallet = ""
