title = "Example Operator Configuration"
description = """
example of how to run a creator node as an operator with audius-d
"""

[Network]
Name = "stage"
Tag = "stage"

[CreatorNodes]

[CreatorNodes.creator-1]
Host = "http://localhost"
Port = 6000
Tag = "latest"
OperatorPrivateKey = ""
Register = true
AwaitHealthy = true
